### ISSUE TITLE
[Crash Report] Colliding entity with block [1.19.2 forge]

### ISSUE THREAD

**Issue by Meskino** [AstralOrdana/Immersive-Weathering#148]
I was just walking through the world and I stepped on a pile of leaves.

Mod version: 1.1.0
Forge Version: 43.1.43
Crash Report: https://hastebin.com/otuqabanuw

**Comment by FreshAlacrity** [comment]
Having a very similar/probably related crash (with many of the same lines in the logs) but without it generating a crash report. 

To replicate: make a new CurseForge profile with IW 1.1.1 and Moonlight 2.0.40 on Forge 43.1.43 for MC 1.19.2, make a new Creative world, plant a Flowering Azalea (happened when planting on both dirt and grass) and bone meal it into a tree, then punch out the wood and wait. 
(Placing and walking through a leaf pile caused no issues for me, though.)

Reported on the server, just adding here to keep things handy in case it helps :)

debug.log - https://gist.github.com/FreshAlacrity/c14f9c1bb4061c2a22b3371fd247b1b3

latest.log - https://gist.github.com/FreshAlacrity/ad4e3858a2bac50af9c9ba594aa48726

**Comment by FreshAlacrity** [comment]
Narrowed this down and with the new update it's crashing more politely:
https://bytebin.lucko.me/vL3RQCKYtP

It's specifically the Flowering Azalea Leaf Piles that are causing the crash, so that explains why stepping on other leaf piles wasn't an issue for me.

Versions:
IW 1.1.2
Moonlight 2.1.0

To replicate: make a new CurseForge profile with IW 1.1.2 and Moonlight 2.1.0 on Forge 43.1.43 for MC 1.19.2, make a new Creative world, place a Flowering Azalea Leaf Pile and walk through it

**Comment by FreshAlacrity** [comment]
For other folks with this issue, I recommend adding 
`leaf_piles_blacklist = ["minecraft:flowering_azalea_leaves"]`
to your config file for the meantime until folks have a chance to get this fixed. That should prevent it from causing problems at least in new worlds unless placing Flowering Azalea Leaf Piles in creative (and Block Swap should be able to help with existing worlds)
