### ISSUE TITLE
Crash with Nether's Exoticism

### ISSUE THREAD

**Issue by IGCBOOM** [AstralOrdana/Immersive-Weathering#61]
Server crashes when entering the nether with nether exoticism installed.

Crash Log:
[crash-2022-05-19_13.56.56-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8733089/crash-2022-05-19_13.56.56-server.txt)

Log: 
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/8733091/latest.log)

**Comment by IGCBOOM** [comment]
Seems to be similar to #59 as well.

**Comment by ground-fruit** [comment]
Running into this as well, also on Forge. Nether's exoticism leaves don't have a persistent parameter. I get the crash when exploring the nether, because I added Nether's Exoticism after initially exploring it.
@IGCBOOM your crash it likely because those leaves were generated when you entered the nether.

Log: [](https://mclo.gs/JUvd2F4), relevant at line 1211
crash report: [](https://mclo.gs/qO2JkRj)

**Comment by IGCBOOM** [comment]
Ya, I tried to fix it and make a PR but I could not get Gradle to work with the forge branch. Terrablender and BOP just refused to be fetched. This can be fixed by using the optional get function and checking if the parameter we are looking for exists.

**Comment by MehVahdJukaar** [comment]
can anybody verify that it still happens?

**Comment by ground-fruit** [comment]
@MehVahdJukaar just tested, all is working for me now. Thanks for your quick development!

**Comment by MaxWasUnavailable** [comment]
> can anybody verify that it still happens?

My issue with the Werewolves mod is still happening.

**Comment by AstralOrdana** [comment]
could you confirm that this has been fixed on 2.5.3?
